# Generated by Django 2.2.1 on 2019-08-07 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aladin_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aladdin_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aladdin_id', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('image_src', models.CharField(max_length=500, null=True)),
                ('price', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('pub_data', models.DateTimeField()),
                ('page', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('publisher_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Book_Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Book')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.Publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Book_Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Book')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Book_Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.Author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Aladin_User_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(null=True)),
                ('time', models.DateTimeField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Aladin_User')),
            ],
        ),
    ]
