# Generated by Django 2.2.1 on 2019-08-07 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aladin_user',
            old_name='aladdin_id',
            new_name='aladin_id',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='aladdin_id',
            new_name='aladin_id',
        ),
    ]
