# Generated by Django 2.2.1 on 2019-09-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20190807_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rec_id',
            field=models.IntegerField(null=True),
        ),
    ]
