# Generated by Django 2.2.1 on 2019-09-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_book_rec_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='rec_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='rec_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='rec_id',
            field=models.IntegerField(null=True),
        ),
    ]
