# Generated by Django 2.2.1 on 2019-11-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_user_book_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lda_sims',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
